<a href="https://colab.research.google.com/github/fidanismayilzada23/Data-Analitc/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a1= np.array([1,2,3,4,5,9,8])
a1

array([1, 2, 3, 4, 5, 9, 8])

In [3]:
a1

array([1, 2, 3, 4, 5, 9, 8])

In [4]:
a1[1:3]

array([2, 3])

In [6]:
a1[-2:]

array([9, 8])

In [7]:
#Arrayin ölçüsü gösterir
a1.shape

(7,)

In [8]:
#Elementin tipini gösterir
a1.dtype

dtype('int64')

In [9]:
# Tipi (array)
type(a1)

numpy.ndarray

In [10]:
#uzunluğunu
a1.size

7

In [14]:
#2d matris array
a2=np.array([[1,2,4],[4,5,6],[6,8,7]])
a2
a2.ndim,a2.shape,a2.dtype,type(a2),a2.size

(2, (3, 3), dtype('int64'), numpy.ndarray, 9)

In [16]:
a2

array([[1, 2, 4],
       [4, 5, 6],
       [6, 8, 7]])

In [17]:
a2[1,2]

np.int64(6)

In [19]:
#Bütün setirler, 2ci sütun
a2[:,1]

array([2, 5, 8])

In [21]:
#sifirdan saymağa başlayır  birinci hissede setirleri sayır : sonra sütunları sayır
a2[2]

array([6, 8, 7])

In [24]:
#1,3 cu setirler, 2 ci sütun seç
a2[1:3,2]

array([6, 7])

In [26]:
#kvadrat mörterze onu vektor şekline salıb deqiq ededleri çıxarir
a2[a2>5]

array([6, 6, 8, 7])

In [32]:
a3=np.array([[[1,2,3],[3,4,6],[4,0,7]],[[4,5,6],[8,6,3],[4,2,1]]])
a3

array([[[1, 2, 3],
        [3, 4, 6],
        [4, 0, 7]],

       [[4, 5, 6],
        [8, 6, 3],
        [4, 2, 1]]])

In [33]:
#(bloklar,setir,sütunlar)
a3.shape

(2, 3, 3)

In [34]:
a3.ndim # 3d array

3

In [35]:
a3.size

18

In [36]:
a3.dtype

dtype('int64')

In [37]:
a3

array([[[1, 2, 3],
        [3, 4, 6],
        [4, 0, 7]],

       [[4, 5, 6],
        [8, 6, 3],
        [4, 2, 1]]])

In [38]:
a3[1,1:,1:]

array([[6, 3],
       [2, 1]])

In [40]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
b=np.arange(0,10)

In [48]:
#arrayı 2 vurur
b*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
 #sıfırdan 10 kimi olan hisseni 5 hisseye bölerek getirir
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [57]:
np.random.seed(42)  #seçilen random ededin olduğu kimi qalsın
random_arr=np.random.randint(1,10,size=(5,3)) # random eded seçir
random_arr

array([[7, 4, 8],
       [5, 7, 3],
       [7, 8, 5],
       [4, 8, 8],
       [3, 6, 5]])

In [61]:
random_arr[1:4,1]

array([7, 8, 8])

In [62]:
random_arr.reshape(3,5)

array([[7, 4, 8, 5, 7],
       [3, 7, 8, 5, 4],
       [8, 8, 3, 6, 5]])

In [64]:
np.random.seed(42)  #seçilen random ededin olduğu kimi qalsın
random_aarr=np.random.randint(1,10,size=(2,5,3)) # random eded seçir
random_aarr

array([[[7, 4, 8],
        [5, 7, 3],
        [7, 8, 5],
        [4, 8, 8],
        [3, 6, 5]],

       [[2, 8, 6],
        [2, 5, 1],
        [6, 9, 1],
        [3, 7, 4],
        [9, 3, 5]]])

In [65]:
random_aarr[:,3:,1:2]

array([[[8],
        [6]],

       [[7],
        [3]]])

In [66]:
a1

array([1, 2, 3, 4, 5, 9, 8])

In [67]:
a1*2

array([ 2,  4,  6,  8, 10, 18, 16])

In [69]:
a2.T

array([[1, 4, 6],
       [2, 5, 8],
       [4, 6, 7]])

In [72]:
np.random.seed(42)  #seçilen random ededin olduğu kimi qalsın
a4=np.random.randint(1,10,size=(2,3)) # random eded seçir
a4

array([[7, 4, 8],
       [5, 7, 3]])

In [73]:
a4.T

array([[7, 5],
       [4, 7],
       [8, 3]])

In [76]:
np.dot(a4,a4.T)  # MATRİSLERİN VURULMASI

array([[129,  87],
       [ 87,  83]])

In [75]:
a4@a4.T  # MATRİSLERİN VURULMASI

array([[129,  87],
       [ 87,  83]])

In [89]:
import time
start=time.time()

arr=np.random.randint(1,10,size=(1_000_0000))**100

end =time.time()
end-start

0.3084847927093506

In [90]:
import time
start=time.time()
result=[]
for i in range (10000000):
  result.append(i**2)
end=time.time()
end-start

1.5750911235809326

In [93]:
np.sum(a4+a4)

np.int64(68)

In [94]:
a2

array([[1, 2, 4],
       [4, 5, 6],
       [6, 8, 7]])